### ISSUE TITLE
Menu doesn't show up after upgrading to Xcode 6.2

### ISSUE THREAD

**Issue by irskep** [scinfu/NCSimulatorPlugin#2]
I've removed and reinstalled the plugin a couple of times. I use Alcatraz.

(Thanks for writing this, by the way!)

**Comment by tanis2000** [comment]
It looks like the GUID has changed. Alcatraz itself suffered from this symptom till yesterday's release. We'll have a look into that issue

**Comment by scinfu** [comment]
Now the plugin is compatible with Xcode 6.2 , uninstall and install new version.
I close the issue .
Feel free to reopen if the problem persists.
