### ISSUE TITLE
The Current App menus open wrong folders

### ISSUE THREAD

**Issue by revolter** [scinfu/NCSimulatorPlugin#4]
Upon clicking `Go To Documents` or `Go To Application` from the `Current App` section, it opens up the folders corresponding to another app.

Also, is it normal to get stuck on `Refreshing...`?

**Comment by scinfu** [comment]
Yes , is normal "Refreshing" state.
Is symptomatic the bug that opens a wrong folder?
I can't reproduce this bug.

**Comment by revolter** [comment]
It works now. I thought it was because I had multiple apps "installed" in the simulator. I'll close this for now and open it if I have more detailed information.

**Comment by revolter** [comment]
It started again. It simply opens up the wrong app's folder to another app that is installed on the simulator.

**Comment by scinfu** [comment]
Fixed in pull request https://github.com/scinfu/NCSimulatorPlugin/pull/7
