### ISSUE TITLE
XCode 6.3 menu doesn't show

### ISSUE THREAD

**Issue by yuriy-makhin** [scinfu/NCSimulatorPlugin#5]
I can force it to show by reinstalling plug-in with Alcatraz, but doing it on every launch gets tiresome.

**Comment by scinfu** [comment]
i have this version Version 6.3.1 (6D1002) and work .
What is your ?

**Comment by yuriy-makhin** [comment]
Version 6.3.2 (6D2105)

**Comment by scinfu** [comment]
ok, i will update my xCode an see where is the incompatibility

**Comment by yuriy-makhin** [comment]
Awesome, thanks for the fix.
